### ISSUE TITLE
View & Modify Acct Settings

### ISSUE THREAD

**Issue by JessicaBruch** [AggielandWebsiteDesign/FosterHuntingClub#10]
Neither link does anything. Don't know if this is intentional at this stage.

**Comment by JT-Bruch** [comment]
If you paid for your account - you have to log out and log back in before anything works...

If you can. can you provide a bit more information on how you were able to reproduce that?

**Comment by JT-Bruch** [comment]
Once your email is confirmed, you pay, and navigate to that screen you should see the following.


![image](https://cloud.githubusercontent.com/assets/7430562/10175353/f07a642a-66b3-11e5-94dc-41c13515498d.png)

**Comment by JT-Bruch** [comment]
Thanks for logging on here btw. Makes abhuge difference

**Comment by JT-Bruch** [comment]
Can not reproduce? :(

**Comment by JT-Bruch** [comment]
Closing because better description in #28
