### ISSUE TITLE
Login link on main navigation menu throws error.

### ISSUE THREAD

**Issue by tbruch** [AggielandWebsiteDesign/FosterHuntingClub#18]
Clicking on the login button when the site is first loaded loads this page:

http://fosterhuntingclub.azurewebsites.net/public/application.html

With the error message:
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

NOTE:  I had not created a user account yet.

**Comment by JT-Bruch** [comment]
Fixed
