### ISSUE TITLE
Copyright in footer should link to AWD and change year automagically.

### ISSUE THREAD

**Issue by tbruch** [AggielandWebsiteDesign/FosterHuntingClub#22]
The Copyright in footer should link to AWD.  It should also automatically change the date based on the year.

This is how it is done on AWD and BSID:

</SCRIPT>

********************************************************/

function copywriteDate(designYear){

var currentYear = new Date().getFullYear()
var displayYear

if (designYear == currentYear) {
	displayYear = designYear
}
else {
	displayYear = (designYear + " - " + currentYear)
}
return (displayYear + " &copy Copyright")
}
// -->

                <SCRIPT language="javascript">
					document.write (copywriteDate(1998));
                </SCRIPT>

**Comment by JT-Bruch** [comment]
Added
