### ISSUE TITLE
When clicking the Login Button, the 'How does this work' page displays for a bit.

### ISSUE THREAD

**Issue by tbruch** [AggielandWebsiteDesign/FosterHuntingClub#24]
1.  On the home page, click the Login Button.
2.  !NOTE the How does this work page displays for a few seconds before the Login dialog displays.

Once this has occurred, it loads faster but you can still see it briefly.  My guess is it is a slow connection page load timing issue.

**Comment by JT-Bruch** [comment]
Yeah actually its an issue with having no authentication data yet and not getting a response back from the server.. Once we get a 401 from the server it kicks us to the login page...

I have a fix for it already :).

**Comment by JT-Bruch** [comment]
Fixed.
