### ISSUE TITLE
Entering an invalid email address throws unfriendly error

### ISSUE THREAD

**Issue by tbruch** [AggielandWebsiteDesign/FosterHuntingClub#25]
1.  Click the Login button.
2.  Enter anything other than an email that is in the system.
!Note the error message "apiError.invalidUsernameOrPassword"

**Comment by JT-Bruch** [comment]
I love actual QA reports. :+1:

**Comment by tbruch** [comment]
Yeah, getting back in the groove!

Thanks!

Tom Bruch
Exceleration Designs, Inc.
http://BigSkyInternetDesign.com

979-776-5160

**Comment by JT-Bruch** [comment]
I can tell!

(Btw - the front page has not received any love since when I did the first pass on it.  Hence the number of bugs)

**Comment by JT-Bruch** [comment]
Fixed
