### ISSUE TITLE
Clicking email confirmation link should take user to Login page.

### ISSUE THREAD

**Issue by tbruch** [AggielandWebsiteDesign/FosterHuntingClub#26]
1.  Register for a new account.
2.  Click on the link in the email to confirm it.
!NOTE: user is redirected to home page.  User should be redirected to the login page, preferably with a message letting them they have been confirmed.

**Comment by JT-Bruch** [comment]
Hey can you see if it the link sent you to localhost instead of fosterhuntingclub.api?

That will happen if I forgot to turn debug mode off on the web.config.

**Comment by tbruch** [comment]
Nope.  The link in the email is:

<a target="_blank" href="
http://fosterhuntingclubapi.azurewebsites.net/api/Account/ConfirmEmail?userId=bcc4ab25-0bae-478a-96af-9f1194faa425&amp;code=6ll5Ra5HAxUNwgcFTarogTmtd0SpeN2Tj8rPtR3VADjJxcre0kNMvwDOxBRIO%2FUxc9d6BN05Ra90E0%2BKJB8Za5fIfOcG2zaFH8Zdaf5mdk1ZeiQGkXrZO1oduo7Q1Mzkau0gbBBhyFER9hounrPkXO6psp46%2FJIVZQtqFAuWJsI1JcI%2BFZkzj8yudRFWt74W
">here</a>

Thanks!

Tom Bruch
Exceleration Designs, Inc.
http://BigSkyInternetDesign.com

979-776-5160

**Comment by JT-Bruch** [comment]
Err.. I mean once you go to that link for the first time, does the next link that show up in the URL show up as the localhost?

**Comment by JT-Bruch** [comment]
Actually that is correct.. I misspoke about the problem but I know what it is and how to fix it.

**Comment by JT-Bruch** [comment]
Fixed :)
