### ISSUE TITLE
Clicking Modify Account Settings causes site to hang

### ISSUE THREAD

**Issue by tbruch** [AggielandWebsiteDesign/FosterHuntingClub#28]
1.  Login to the site.
2.  Do not pay for it yet (not sure if this is part of it or not).
3.  Click on the Modify Account Setting link.
!NOTE the site hangs and the user must close the session.

**Comment by tbruch** [comment]
Clicking on any of the navigation links on the left side bar will also cause it to hang.

**Comment by tbruch** [comment]
Clicking on the links with the exception of  Logout under the email address of the user (top right) causes it to hang.

**Comment by JT-Bruch** [comment]
Ahh that must be what Jess meant in #10

**Comment by tbruch** [comment]
Yeah, it was just a little vague!

Thanks!

Tom Bruch
Exceleration Designs, Inc.
http://BigSkyInternetDesign.com

979-776-5160

**Comment by JT-Bruch** [comment]
Fixed this bad boy!
