### ISSUE TITLE
Changing password does not verify current password is correct.

### ISSUE THREAD

**Issue by tbruch** [AggielandWebsiteDesign/FosterHuntingClub#32]
1.  Login to the site.
2.  Click on View Account Settings.
3.  Click on Change Password.
4.  Enter an incorrect password for the current password.
5.  Enter whatever for the new password and click Change Password.
! NOTE the current password is not verified so the user does not know what they did wrong.

**Comment by JT-Bruch** [comment]
This now works beautifully
