### ISSUE TITLE
Payment history Invoice is a link, but it does not load the invoice.

### ISSUE THREAD

**Issue by tbruch** [AggielandWebsiteDesign/FosterHuntingClub#33]
1.  Login and navigate to View Payment History.
!NOTE the invoice number is underlined, however the link does not do anything.

**Comment by JT-Bruch** [comment]
Actually there is no invoice.. Just a list of charges..

Was not designed to have an invoice...

**Comment by tbruch** [comment]
Gotcha.  Figured that.  Would suggest removing the <a> tags around it so it
does not appear to be a link.

Thanks!

Tom Bruch
Exceleration Designs, Inc.
http://BigSkyInternetDesign.com

979-776-5160

**Comment by JT-Bruch** [comment]
Yeah when I removed the href I meant to change them to <strong> instead but got distracted with something else. 

Thanks for going through this BTW.

**Comment by tbruch** [comment]
You bet.  Kind of enjoying it!

Thanks!

Tom Bruch
Exceleration Designs, Inc.
http://BigSkyInternetDesign.com

979-776-5160

**Comment by JT-Bruch** [comment]
Fixed
