### ISSUE TITLE
Register

### ISSUE THREAD

**Issue by cbruch** [AggielandWebsiteDesign/FosterHuntingClub#8]
Registration failed: An error has occurred.

**Comment by JT-Bruch** [comment]
Hmm.

Can you provide a bit more information on what happened when that occurred.   Both Jess & Kristen were able to register and create accounts.

**Comment by cbruch** [comment]
First time I tried to register, I auto filled & the phone number was not
like in example (xxx)-xxx-xxxx, did not notice it was wrong. Then hit
register & said passwords did not match. So I redid PW & fixed phone
number, it would not let me register.

Does that help??


Thank you,
Carrie Bruch


Big Sky Internet Design, Inc.
Web Design for the Future....

Hours 8-5 pm Central
979-776-5160

32 Raven Dr
Bryan, Texas 77808

**Comment by JT-Bruch** [comment]
Yup. I think it's because the phone number example is incorrect and needs only numbers. Can you try that? I'll fix it tonight

**Comment by JT-Bruch** [comment]
Thanks for logging the issues here. Makes a world of difference.

**Comment by cbruch** [comment]
I tired again with the auto fill phone number & it still do not let me register. Then I went back out & tried again with just the zip code 77808, without the -917 & I think that might have worked. But I did get the email confirming crb@rockinb.com

Then I registered carrie@aggielandwebsitedesign.com  All phone number together & NO extra numbers on zip code & that was the happy camper!

**Comment by JT-Bruch** [comment]
Awesome yeah I will update the error message to detail what happened.

Also I assigned both your accounts to two different leases.

**Comment by JT-Bruch** [comment]
Fixed :)
