### ISSUE TITLE
Home

### ISSUE THREAD

**Issue by cbruch** [AggielandWebsiteDesign/FosterHuntingClub#9]
When on login page & try & go back home the page just jumps. You can kind of see it say "How it works, but never goes any where.

**Comment by JT-Bruch** [comment]
Is this before or after registration failed?

**Comment by cbruch** [comment]
After.

Thank you,
Carrie Bruch


Big Sky Internet Design, Inc.
Web Design for the Future....

Hours 8-5 pm Central
979-776-5160

32 Raven Dr
Bryan, Texas 77808

**Comment by JT-Bruch** [comment]
Fixed it by adding a smooth loading transition.
